FROM node:22-alpine

WORKDIR /app


COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/ws-backend ./apps/ws-backend

RUN npm install -g pnpm


RUN pnpm install --frozen-lockfile --workspace-root


WORKDIR /app/apps/ws-backend


RUN pnpm run build

EXPOSE 8080

CMD ["node", "dist/index.js"]

