name: CD Backend

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build & Push Backend Docker Image
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

   
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.backend
          push: true
          tags: |
            sameerv066/collab-draw-backend:latest
            sameerv066/collab-draw-backend:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      # Verify built image (optional but good practice)
      # - name: Verify Docker image
      #   run: |
      #     docker pull sameerv066/collab-draw-backend:${{ github.sha }}
      #     docker image inspect sameerv066/collab-draw-backend:${{ github.sha }}
