name: CD Websocket

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build & Push Websocket Docker Image
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

   
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.websocket
          push: true
          tags: |
            sameerv066/collab-draw-websocket:latest
            sameerv066/collab-draw-websocket:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}


